Combobox: Only set value from data store items, otherwise set to “”.
Set value to “” when user starts typing or backspacing until user
selects a choice from the dropdown.  Avoids ambiguity where a value of
“123” could mean either that the user typed “123”, or that the user
typed “foo”, matching an item like {id: “123”, label: “foo”}.

Application code that sets a value must now also set displayedValue,
even if the source items don’t have separate label and id properties.
Exception: if zero or multiple items are selected Combobox will set the
right label automatically.

Also note that the "input" event occurs much less frequently now, since
Comobobox#value no longer changes on every keystroke.
(The "input" event is tied to value rather than displayedValue.)

If we want an auto-complete widget where value is whatever is in the
<input> (and the source items only contains labels, not ids), then that
could be a subclass of Combobox.

Fixes #699.