Upgrade to Intern 4 and fix various test problems.
Changes include:

- Tests are now run directly from "npx intern".
- iOS disabled due to theintern/intern#981.
- List of tests inlined into intern.json to make order deterministic.
- Commented out some broken code in RadioButton test, already marked with a TODO.
- SidePane functional test: Rewrote to address many issues, most importantly
  that it was calling isVisible() too soon.
- StarRating functional test: Fixed missing return statements breaking async chaining.
- Fixed missing return statements in StarRating, Toaster, ScrollableContainer functional
  tests causing new test to start prematurely and weird unhandled exceptions to occur.

Has more-or-less the same failures that it used to.
I'm mainly ignoring the Edge failures, since the Edge internals will soon be switched to Chromium,
and the IE failures, since IE is near EOL.

Unit tests failures on Saucelabs:

Edge - multiple timeouts in ViewStack tests

× MicrosoftEdge on windows 10 - list/PageableList-ObservableArray - autoPaging: categorized list with category headers destroyed when loading pages (7.071s)
    TimeoutError: Timeout reached on MicrosoftEdge on windows 10 - list/PageableList-ObservableArray - autoPaging: categorized list with category headers destroyed when loading pages#

× MicrosoftEdge on windows 10 - list/PageableList - autoPaging: categorized list with category headers destroyed when loading pages (10.06s)
    TimeoutError: Timeout reached on MicrosoftEdge on windows 10 - list/PageableList - autoPaging: categorized list with category headers destroyed when loading pages#

× chrome 75.0.3770.80 on Windows NT - list/PageableList-ObservableArray - autoPaging: categorized list with category headers destroyed when loading pages (0.385s)
    AssertionError: last visible renderer after second page load: expected 'Category 5' to equal 'item 73'

× chrome 75.0.3770.80 on Windows NT - list/PageableList - autoPaging: categorized list with category headers destroyed when loading pages (1.065s)
    AssertionError: last visible renderer after second page load: expected 'Category 5' to equal 'item 73'

Functional tests failures on SauceLabs:

× internet explorer 11 on WINDOWS - Combobox - functional - mouse navigation selectionMode=single, autoFilter=false (9.19s)
    AssertionError: combo1 (single) after clicking the third option (Germany) inputNodeValue: expected 'France' to equal 'Germany'

× internet explorer 11 on WINDOWS - Combobox - functional - mouse navigation selectionMode=multiple (11.679s)
    AssertionError: combo3 (multiple) after clicking the third item (Germany)) inputNodeValue: expected 'Select option(s)' to equal '2 selected'

× internet explorer 11 on WINDOWS - Combobox - functional - popup position after filter (11.187s)
    JavaScriptError: [POST http://(redacted)@localhost:4444/wd/hub/session/622427867218441789dd1c603d3a47b5/execute / {"script":"return isAligned(\"combo2-custom-sel-single\", \"above\")","args":[]}] JavaScript error (WARNING: The server did not provide any stacktrace information)

× chrome 75.0.3770.80 on Windows NT - Pageable tests - Pageable list keyboard navigation (12.469s)
    AssertionError: loadNext #2 (b): expected 'Programmatic item of order 40' to equal 'Programmatic item of order 59'

× chrome 75.0.3770.80 on Windows NT - Pageable tests - Pageable categorized list keyboard navigation (10.019s)
    AssertionError: loadNext #2 (b): expected 'Category 5' to equal 'Programmatic item of order 73'

Also, Chrome on SauceLabs tends to fail at the end, usually in Tooltip but it could be in Switch.
It works when run locally.