Preparation for Intern 4 conversion, and numerous lint fixes.
Changes include:

- Use CommonJS-ish form of AMD. (Thanks amd-to-common!)
- Remove unused imports.
- Fix reused variable names, inconsistent quoting, etc.

Chrome has the same failures as usual:

× chrome on any platform - unit tests - list/PageableList-ObservableArray - autoPaging: categorized list with category headers destroyed when loading pages (0.38s)
AssertionError: last visible renderer after second page load: expected 'Category 5' to equal 'item 73'

× chrome on any platform - unit tests - list/PageableList - autoPaging: categorized list with category headers destroyed when loading pages (1.072s)
AssertionError: last visible renderer after second page load: expected 'Category 5' to equal 'item 73'

× chrome on any platform - Pageable tests - Pageable list keyboard navigation (0.814s)
AssertionError: loadNext #2 (b): expected 'Programmatic item of order 40' to equal 'Programmatic item of order 59'

× chrome on any platform - Pageable tests - Pageable categorized list keyboard navigation (0.788s)
AssertionError: loadNext #2 (b): expected 'Category 5' to equal 'Programmatic item of order 73'

In addition, I noticed the toaster tests seem to hang (70s or 30s to execute a single test),
but there's no error reported.